appName: adservice
appImage: gcr.io/google-samples/microservices-demo/adservice
appVersion: v0.8.1
appReplicas: 1
containerPort: 9555
containerEnvVars:
- name: PORT
  value: "9555"

servicePort: 9555
serviceType: ClusterIP