appName: currencyservice
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.8.1
appReplicas: 1
containerPort: 7000
containerEnvVars:
- name: PORT
  value: "7000"

servicePort: 7000
serviceType: ClusterIP