appName: shippingservice
appImage: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v0.8.1
appReplicas: 1
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"

servicePort: 50051
serviceType: ClusterIP